version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'dev'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    groups:
      routine-updates:
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: '⬆️'

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'dev'
    schedule:
      interval: 'weekly'
      day: 'monday'
    labels:
      - 'dependencies'
      - 'ci'
    commit-message:
      prefix: '⬆️'
